namespace SsiGroup.ProjectUsNormalizer.Constants;

/// <summary>
///   The US states and territories.
/// </summary>
internal static class States
{
  /// <summary>
  ///   2-letter abbreviations of the US states and territories.
  /// </summary>
  internal static IReadOnlyDictionary<string, string> Abbreviations = new Dictionary<string, string>
  {
    { "ALABAMA", "AL" },
    { "ALASKA", "AK" },
    { "AMERICAN SAMOA", "AS" },
    { "ARIZONA", "AZ" },
    { "ARKANSAS", "AR" },
    { "CALIFORNIA", "CA" },
    { "COLORADO", "CO" },
    { "CONNECTICUT", "CT" },
    { "DELAWARE", "DE" },
    { "DISTRICT OF COLUMBIA", "DC" },
    { "FEDERATED STATES OF MICRONESIA", "FM" },
    { "FLORIDA", "FL" },
    { "GEORGIA", "GA" },
    { "GUAM", "GU" },
    { "HAWAII", "HI" },
    { "IDAHO", "ID" },
    { "ILLINOIS", "IL" },
    { "INDIANA", "IN" },
    { "IOWA", "IA" },
    { "KANSAS", "KS" },
    { "KENTUCKY", "KY" },
    { "LOUISIANA", "LA" },
    { "MAINE", "ME" },
    { "MARSHALL ISLANDS", "MH" },
    { "MARYLAND", "MD" },
    { "MASSACHUSETTS", "MA" },
    { "MICHIGAN", "MI" },
    { "MINNESOTA", "MN" },
    { "MISSISSIPPI", "MS" },
    { "MISSOURI", "MO" },
    { "MONTANA", "MT" },
    { "NEBRASKA", "NE" },
    { "NEVADA", "NV" },
    { "NEW HAMPSHIRE", "NH" },
    { "NEW JERSEY", "NJ" },
    { "NEW MEXICO", "NM" },
    { "NEW YORK", "NY" },
    { "NORTH CAROLINA", "NC" },
    { "NORTH DAKOTA", "ND" },
    { "NORTHERN MARIANA ISLANDS", "MP" },
    { "OHIO", "OH" },
    { "OKLAHOMA", "OK" },
    { "OREGON", "OR" },
    { "PALAU", "PW" },
    { "PENNSYLVANIA", "PA" },
    { "PUERTO RICO", "PR" },
    { "RHODE ISLAND", "RI" },
    { "SOUTH CAROLINA", "SC" },
    { "SOUTH DAKOTA", "SD" },
    { "TENNESSEE", "TN" },
    { "TEXAS", "TX" },
    { "UTAH", "UT" },
    { "VERMONT", "VT" },
    { "VIRGIN ISLANDS", "VI" },
    { "VIRGINIA", "VA" },
    { "WASHINGTON", "WA" },
    { "WEST VIRGINIA", "WV" },
    { "WISCONSIN", "WI" },
    { "WYOMING", "WY" }
  };

  /// <summary>
  ///   Fully spelled out the US states and territories.
  /// </summary>
  internal static IReadOnlyDictionary<string, string> FullySpelledOut = new Dictionary<string, string>
  {
    { "AK", "ALASKA" },
    { "AL", "ALABAMA" },
    { "AR", "ARKANSAS" },
    { "AS", "AMERICAN SAMOA" },
    { "AZ", "ARIZONA" },
    { "CA", "CALIFORNIA" },
    { "CO", "COLORADO" },
    { "CT", "CONNECTICUT" },
    { "DE", "DELAWARE" },
    { "DC", "DISTRICT OF COLUMBIA" },
    { "FM", "FEDERATED STATES OF MICRONESIA" },
    { "FL", "FLORIDA" },
    { "GA", "GEORGIA" },
    { "GU", "GUAM" },
    { "HI", "HAWAII" },
    { "ID", "IDAHO" },
    { "IL", "ILLINOIS" },
    { "IN", "INDIANA" },
    { "IA", "IOWA" },
    { "KS", "KANSAS" },
    { "KY", "KENTUCKY" },
    { "LA", "LOUISIANA" },
    { "MA", "MASSACHUSETTS" },
    { "ME", "MAINE" },
    { "MD", "MARYLAND" },
    { "MI", "MICHIGAN" },
    { "MH", "MARSHALL ISLANDS" },
    { "MN", "MINNESOTA" },
    { "MO", "MISSOURI" },
    { "MS", "MISSISSIPPI" },
    { "MT", "MONTANA" },
    { "NE", "NEBRASKA" },
    { "NV", "NEVADA" },
    { "NH", "NEW HAMPSHIRE" },
    { "NJ", "NEW JERSEY" },
    { "NM", "NEW MEXICO" },
    { "NY", "NEW YORK" },
    { "NC", "NORTH CAROLINA" },
    { "ND", "NORTH DAKOTA" },
    { "MP", "NORTHERN MARIANA ISLANDS" },
    { "OH", "OHIO" },
    { "OK", "OKLAHOMA" },
    { "OR", "OREGON" },
    { "PW", "PALAU" },
    { "PA", "PENNSYLVANIA" },
    { "PR", "PUERTO RICO" },
    { "RI", "RHODE ISLAND" },
    { "SC", "SOUTH CAROLINA" },
    { "SD", "SOUTH DAKOTA" },
    { "TN", "TENNESSEE" },
    { "TX", "TEXAS" },
    { "UT", "UTAH" },
    { "VA", "VIRGINIA" },
    { "VI", "VIRGIN ISLANDS" },
    { "VT", "VERMONT" },
    { "WA", "WASHINGTON" },
    { "WI", "WISCONSIN" },
    { "WV", "WEST VIRGINIA" },
    { "WY", "WYOMING" }
  };
}
